### PR TITLE
[WIP] Include options

### PR DESCRIPTION
**Pull request by dvarrazzo**
This branch adds options to select/exclude certain tables from replication. It is a work in progress: submitting to check if there is interest in this feature.

Features to add:

- [ ] handle include/exclude schemas
- [ ] decide a syntax or different options to specify schemas and tables as simple names or as regexp
- [ ] add option to include/exclude fields on a table
- [x] add a cache to store the comparison result

### CODE REVIEW

**Comment by dvarrazzo** [comment]
Note: initial commits are subjects of other merge requests: to be rebased away.

**Comment by dvarrazzo** [comment]
Closing this MR as I think this feature surpasses the original scope of the plugin.

**Comment by eulerto** [comment]
@dvarrazzo I'm interested in some of those commits. Can I merge some of them?

**Comment by dvarrazzo** [comment]
Of course: take whatever you find useful.

**Pull request closed without merging**
