### PR TITLE
Restore memory context on change decode early bailout

### LINKED ISSUE #10: (maybe) wrong memory context?
More a question than a bug report, as I don't know many details of Postgres allocator:

```c
pg_decode_change(LogicalDecodingContext *ctx, ReorderBufferTXN *txn,
				 Relation relation, ReorderBufferChange *change)

	/* ... */

	old = MemoryContextSwitchTo(data->context);

	/* ... */

	switch (change->action)
	{
		case REORDER_BUFFER_CHANGE_INSERT:
			if (change->data.tp.newtuple == NULL)
			{
				elog(WARNING, "no tuple data for INSERT in table \"%s\"", NameStr(class_form->relname));
				return;
			}
			break;

	/* ... */

	MemoryContextSwitchTo(old);
	MemoryContextReset(data->context);
}
```

if the return is early, isn't the memory context left in an inconsistent state?

Thank you.

### PR DESCRIPTION
**Pull request by dvarrazzo**
Close #10

### CODE REVIEW

**Comment by eulerto** [comment]
@dvarrazzo this patch does not seem to be correct. You moved the MemoryContext code to goto block to cover error condition, however, in normal execution the MemoryContext functions will not be called. Do not remove MemoryContext function calls before "if (data->write_in_chunks)". Also, rename the goto label to action_err, change_err or failed because "exit" is a generic name and a function name.

**Comment by dvarrazzo** [comment]
Yes, it will be called: the program flow will fall through the exit label.

I've renamed the label as `reset_ctx`. It is not really an error handler (as the normal program flow will call it too).

**Comment by eulerto** [comment]
@dvarrazzo You are changing the original execution order. Since we can't control OutputPluginWrite, I think it is too risky to assume that resetting context after OutputPluginWrite will cause some trouble. AFAICS, it wouldn't but I prefer to maintain the reset **before** call OutputPluginWrite.

I apply a different patch (commit ea2b35abad0793ffc53820f027a5ed61c774c99b).

**Comment by dvarrazzo** [comment]
ISTM that deallocating the context *after* it is used is the right way of working. Anyway, no problem for me.

**Pull request closed without merging**
