### PR TITLE
Add schema and table filter

### PR DESCRIPTION
**Pull request by notxcain**
Refs #48 

It's been a while since I touched `C`, so comments are welcome.
It's a draft, so naming is not final yet. I just wanted to be sure that this is the right direction.

### CODE REVIEW

**Comment by goldfix** [comment]
If you interested I added a similar solution in my branch: https://github.com/goldfix/wal2json

You are welcome to contribute, improve or inspire you :-)

ciao
p

**Comment by Fxlr8** [comment]
Why is this not merged yet?

**Comment by Fxlr8** [comment]
@goldfix, I have tried your implementation and it outputs empty arrays of data when the filter is enabled. There was no way to create an issue at your fork, so I leave it here

**Comment by goldfix** [comment]
Hi @Fxlr8 ,

please open an issue on my branch (I opened issues).

thanks

p

**Comment by Fxlr8** [comment]
@notxcain my bad, it should be `filter-table=public.messages` instead of `filter-table="messages"`. BTW is it possible to pass multiple tables?

**Comment by eulerto** [comment]
@Fxlr8 because it doesn't handle all cases (cf. @rcoup comment in #48). I've committed a different patch (cf. 409fcff4478743d161eb0358d26930773335767a) that handles all special cases (such as schemas and/or tables with spaces, single quotes, commas, periods).

**Pull request closed without merging**
