### PR TITLE
Use TupleDescAttr() accessor, mandatory for pg11+

### PR DESCRIPTION
**Pull request by rjuju**

### CODE REVIEW

**Comment by eulerto** [comment]
@rjuju Yes, I've already noticed that API breakage and would push a fix when the dust settles down. Since you submitted a PR, I would ask you to change the commit message adding the commit info (only the SHA) that causes this code change.

commit 2cd70845240087da205695baedab6412342d1dbe
Author: Andres Freund <andres@anarazel.de>
Date:   Sun Aug 20 11:19:07 2017 -0700

    Change tupledesc->attrs[n] to TupleDescAttr(tupledesc, n).
    
    This is a mechanical change in preparation for a later commit that
    will change the layout of TupleDesc.  Introducing a macro to abstract
    the details of where attributes are stored will allow us to change
    that in separate step and revise it in future.

**Comment by rjuju** [comment]
@eulerto yes, I also usually wait a little bit before adding compatibility, but since this one is an infrastructure change that's already used, I don't think it'll get changed or renamed.

I updated the commit message to mention the upstream commit adding this macro, and the commit making it mandatory, is the message ok for you?

**Comment by eulerto** [comment]
Sure. I have merged your PR. Thanks for your patch.

**Comment by rjuju** [comment]
Thanks!

**Comment by rjuju** [comment]
Actually, I can't find new commit on HEAD and this PR is shown as closed without merging, did I miss something?

**Pull request closed without merging**
