### PR TITLE
Add individual row LSNs to output.

### PR DESCRIPTION
**Pull request by erikvanzijst**
This change adds an option to include the individual WAL location
(ReorderBufferChange->lsn) of each insert/update/delete statement in
the JSON change object.

    {
    	"change": [
    		{
    			"lsn": "0/1738B00",
    			"kind": "insert",
    			"schema": "public",
    			"table": "groups_group_members",
    			"columnnames": ["id", "group_id", "user_id"],
    			"columnvalues": [1, 1, 4]
    		}
      ]
    }

### CODE REVIEW

**Comment by erikvanzijst** [comment]
The motivation behind this that we are planning on using wal2json as part of a custom, internal logical replication system in Bitbucket. This system does not anchor on transaction boundaries, but relies on the LSNs of individual records.

**Comment by erikvanzijst** [comment]
Does this PR look roughly ok?

**Comment by rkrage** [comment]
@eulerto, this is also something we'd love to have. Thoughts?

**Comment by eulerto** [comment]
@erikvanzijst Great! That is something I have in my roadmap. However, you should include a test and rename the parameter to `include-change-lsn`.

**Comment by erikvanzijst** [comment]
@eulerto I've renamed to switch to `include-change-lsn` as suggested.

I also wrote a REGRESS script, but since the actual value of the LSN in the output is not guaranteed to be stable, I have not included the test.

It looks like PGXS is not really capable of assertions against output containing dynamic elements. It looks like 2ndquadrant has done some work on using [TAP](https://testanything.org/) for this (https://blog.2ndquadrant.com/using-postgresql-tap-framework-extensions/) but I'm not sure how common that is and whether or not you would want to add such dependency.

How would you like me to move forward? I'm happy to try and switch the REGRESS tests to use TAP, or maybe you have a more elegant approach?

**Comment by erikvanzijst** [comment]
> How would you like me to move forward? I'm happy to try and switch the REGRESS tests to use TAP, or maybe you have a more elegant approach?

I've taken the same approach @dpirotte took in `include_lsn.sql` where we keep the actual LSN value out of the output and instead assert that that the lsn attribute is present and distinct for each row in pg_logical_slot_get_changes.

**Comment by erikvanzijst** [comment]
Not sure if there are any automated tests, but the tests pass against 9.6.11 on Linux:

```
postgres@349e047558a4:/src$ make installcheck
/usr/lib/postgresql/9.6/lib/pgxs/src/makefiles/../../src/test/regress/pg_regress --inputdir=./ --bindir='/usr/lib/postgresql/9.6/bin'    --dbname=contrib_regression cmdline insert1 update1 update2 update3 update4 delete1 delete2 delete3 delete4 savepoint specialvalue toast bytea message typmod filtertable selecttable include_timestamp include_lsn include_xids include_change_lsn
(using postmaster on Unix socket, default port)
============== dropping database "contrib_regression" ==============
DROP DATABASE
============== creating database "contrib_regression" ==============
CREATE DATABASE
ALTER DATABASE
============== running regression test queries        ==============
test cmdline                  ... ok
test insert1                  ... ok
test update1                  ... ok
test update2                  ... ok
test update3                  ... ok
test update4                  ... ok
test delete1                  ... ok
test delete2                  ... ok
test delete3                  ... ok
test delete4                  ... ok
test savepoint                ... ok
test specialvalue             ... ok
test toast                    ... ok
test bytea                    ... ok
test message                  ... ok
test typmod                   ... ok
test filtertable              ... ok
test selecttable              ... ok
test include_timestamp        ... ok
test include_lsn              ... ok
test include_xids             ... ok
test include_change_lsn       ... ok

======================
 All 22 tests passed. 
======================

postgres@349e047558a4:/src$ 
```

**Comment by erikvanzijst** [comment]
Let me know if this looks like what you had in mind.

**Comment by eulerto** [comment]
@erikvanzijst I don't have time to take a look at your PR right now. I'm concentrating efforts in the new format ( PR #110 ). BTW, LSN is on radar, although I don't include it yet.

**Pull request closed without merging**
