### PR TITLE
Add an optional new output format

### PR DESCRIPTION
**Pull request by addisonj**
This adapts the work done for `write-in-chunks` to add a new output
format, called `msg-per-record` this produces an entire newline
delimited json record for every individual change.

This is useful for large transactions while also making the output
easier to parse. As it currently exists with `write-in-chunks`, the
slot consumer needs to either buffer the entire record or implement more
complex stream parsing to handle the changes.

The new format is outlined in the README, but essentially we add two new
`kinds` of records - `begin` and `commit` and then output the elements
of the `changes` arrary as individual documents.

### CODE REVIEW

**Comment by rcoup** [comment]
@addisonj could it use [RFC7464](https://tools.ietf.org/html/rfc7464) output?

> In prose: any number of JSON texts, each encoded in UTF-8 [RFC3629], each preceded by one ASCII RS character, and each followed by a line feed (LF).  Since RS is an ASCII control character, it may only appear in JSON strings in escaped form (see [RFC7159]), and since RS may not appear in JSON texts in any other form, RS unambiguously delimits the start of any element in the sequence.  RS is sufficient to unambiguously delimit all top-level JSON value types other than numbers.  Following each JSON text in the sequence with an LF allows detection of truncated JSON texts consisting of a number at the top-level; see Section 2.4.

**Comment by addisonj** [comment]
@rcoup Maybe could be made as an option? But having dealt with a lot of streaming json over the years... I honestly haven't come across that RFC actually being used all that much.

jsonlines (http://jsonlines.org/on_the_web/) is by far what I see a lot of people using for streaming json, and that link gives a few good examples of existing streaming json support. I would also add that even for just saving to flat files, tools like apache spark default to newline delimited json and the newline also makes it a lot easier to read the file with just a text editor.

It might make sense to have it go into that mode if `pretty-print` is also defined, as most of what I said above only really applies to compact (single line) json format and is obviously incompatible with pretty priting. That would negate the need for yet another option, but might be sort of "magical" behavior. Another option wouldn't be terrible either, should be pretty easy to implement.

Personally... I would advocate for removing `pretty-print` from wal2json as it adds a lot of complexity to the code and is easy to recreate by shoving the wal2json output through any number of json tools. This would then allow this new output format to simply output newline delimited json unambiguously.

**Comment by rcoup** [comment]
> Personally... I would advocate for removing pretty-print from wal2json as it adds a lot of complexity to the code and is easy to recreate by shoving the wal2json output through any number of json tools. This would then allow this new output format to simply output newline delimited json unambiguously.

👍

**Comment by eulerto** [comment]
@jpfuentes2 @addisonj I didn't have time to look into it yet. I realized that the format has some limitations for big transactions (that's why I added `--write-in-chunks` ). This is more or less the format I initially worked for wal2json but I chose the actual format instead. The reason for choosing the actual format were: (i) simple replication client (the client state machine is simpler with the actual format than the proposed format because I can consume the JSON object as soon as it arrives. The proposed format needs to wait the final JSON object to consume the transaction) and (ii) transactions tend to be small in average and (iii) transactions conform with json(b) data type (that is important because some clients load the stream of transaction into postgres. Per a comment above, it seems the proposed PR does not about conformance. I don't want to change this concept for `wal2json`.).

**Comment by jpfuentes2** [comment]
@addisonj are you still interested in seeing this work through? 

> Personally... I would advocate for removing pretty-print from wal2json as it adds a lot of complexity to the code and is easy to recreate by shoving the wal2json output through any number of json tools. This would then allow this new output format to simply output newline delimited json unambiguously.

@eulerto what are your thoughts there? FWIW, I agree with this sentiment. Would you be interested in accepting a PR to remove the functionality?

**Comment by jpfuentes2** [comment]
> I'm not convinced that pretty-print is not useful. I use it a lot to check transaction data on psql.

Can't that be achieved thru PG JSON functions easily enough?

```sql
create table demo (id bigserial primary key);

insert into demo (id) values (default);

select jsonb_pretty(data::jsonb) from pg_logical_slot_peek_changes('example', null, null) limit 1;
+----------------+
| jsonb_pretty   |
|----------------|
| {
    "xid": 570997,
    "table": "public.demo",
    "types": [
        "int8"
    ],
    "values": [
        1
    ],
    "columns": [
        "id"
    ],
    "operation": "insert",
    "timestamp": "2018-06-22 11:38:45.835991-04"
}                |
+----------------+
```

When not done in a PSQL context then as mentioned earlier there exists a plethora of CLI tooling (looking at `jq` here) to do this for us.

Setting the `pretty-print` conversation aside: would you accept this patch if it's fixed up? Do you foresee any blockers/problems that'd prevent you from accepting this option and new output format?

**Comment by eulerto** [comment]
> Can't that be achieved thru PG JSON functions easily enough?

Yes, but the problem is that `jsonb_pretty` is not available in 9.4 (that is a supported postgres version).

> Setting the pretty-print conversation aside: would you accept this patch if it's fixed up?

I would definitely consider this patch.

> Do you foresee any blockers/problems that'd prevent you from accepting this option and new output format?

No. It seems straightforward.

**Comment by jpfuentes2** [comment]
> Yes, but the problem is that jsonb_pretty is not available in 9.4 (that is a supported postgres version).

_slaps forehead_. You're right, I'm stuck in my happy place land where we're at least on 9.6 everywhere :).

> No. It seems straightforward.

Great! Unless @addisonj comes back really soon on this I will take the work here and start a new PR fixing up that conflict and will attribute to @addisonj.

**Comment by rkrage** [comment]
@jpfuentes2 this is something we'd like to have as well. Any updates?

**Comment by addisonj** [comment]
This has been on my back burner for a while, had some other higher priority stuff come up, I will be back at this in the next couple of weeks, if there isn't an up-to-date PR by then from @jpfuentes2 I am happy to take another crack at it then.

**Comment by eulerto** [comment]
The commit 1b0cbac484f4fe5db80445f6721957511b4de7b7 added a new format that is one-json-per-tuple.

**Pull request closed without merging**
