### PR TITLE
Skip empty xacts

### PR DESCRIPTION
**Pull request by dvarrazzo**
This merge request adds the option to skip empty transactions. The first commit is the subject of MR #11: it's included here because without that running tests is impossible. If that's merged before I can rebase this branch.

### CODE REVIEW

**Comment by eulerto** [comment]
@dvarrazzo Could you rebase this branch since I merged #11?

**Comment by dvarrazzo** [comment]
Rebased.

**Comment by dvarrazzo** [comment]
Note: I think the default for this option should be true, at least if the default for display-xids is false. That depends on #17 and on whether you are fine with changing the default output.

**Comment by eulerto** [comment]
@dvarrazzo Please fix the following items:
* add a message "elog(LOG, "skip-empty-xacts argument is null")" in pg_decode_startup();
* move function declaration (output_begin) to the top;
* OutputPluginPrepareWrite(ctx, true) -> OutputPluginPrepareWrite(ctx, last_write) at the begining of output_begin (BTW output_begin could be pg_output_begin as in test_decoding).

**Comment by dvarrazzo** [comment]
> add a message "elog(LOG, "skip-empty-xacts argument is null")" in pg_decode_startup();

done

> move function declaration (output_begin) to the top;

done

> OutputPluginPrepareWrite(ctx, true) -> OutputPluginPrepareWrite(ctx, last_write) at the begining of output_begin 

oops. Done.

> (BTW output_begin could be pg_output_begin as in test_decoding).

I think instead that `pg_` prefix should be dropped: this is a postgres extension, not postgres itself.
A few callbacks are also missing the `static` specification on the definition (see https://github.com/dvarrazzo/wal2json/commit/800cfb6e). It is on the declaration though.

**Pull request closed without merging**
